-- CRSOFT.StockCrawler -- PostgreSQL-Schema, Stand der SQL-Server-Migrationen 010 bis 043.
-- Erzeugt aus dem Katalog der laufenden SQL-Server-Datenbank; von Hand nachgezogen,
-- wo Postgres etwas anderes braucht (Routinen, berechnete Spalten, Pruefbedingungen).
-- Idempotent: ein zweiter Lauf schadet nicht.
--
-- Schema dbo: damit die 300 "dbo."-Praefixe im Code unveraendert bleiben. Der
-- Suchpfad der Verbindung sollte "dbo, public" sein (Search Path=dbo,public in der
-- Verbindungszeichenfolge); dann finden auch unqualifizierte Namen ihr Ziel.
--
-- Zeitspalten sind timestamp OHNE Zeitzone -- die Anwendung rechnet in UTC und
-- Npgsql laeuft mit EnableLegacyTimestampBehavior (siehe SqlConnectionFactory).

CREATE SCHEMA IF NOT EXISTS dbo;
SET search_path = dbo, public;

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.app_session (
  "session_key" uuid NOT NULL,
  "user_id" integer,
  "created_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "last_seen_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "expires_utc" timestamp(0),
  CONSTRAINT "PK_app_session" PRIMARY KEY ("session_key")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.app_state (
  "owner_kind" smallint NOT NULL,
  "owner_key" varchar(64) NOT NULL,
  "area" varchar(64) NOT NULL,
  "payload" text NOT NULL,
  "updated_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  CONSTRAINT "PK_app_state" PRIMARY KEY ("owner_kind", "owner_key", "area")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.app_user (
  "user_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "login" varchar(128) NOT NULL,
  "display_name" varchar(128),
  "created_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "password_hash" varchar(400),
  "role" varchar(16) NOT NULL DEFAULT 'user',
  "is_active" boolean NOT NULL DEFAULT true,
  "last_login_utc" timestamp(0),
  "failed_logins" integer NOT NULL DEFAULT 0,
  "locked_until_utc" timestamp(0),
  CONSTRAINT "PK_app_user" PRIMARY KEY ("user_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.asset (
  "asset_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "asset_class" smallint NOT NULL,
  "symbol" varchar(64) NOT NULL,
  "name" varchar(200),
  "currency" varchar(10),
  "exchange" varchar(64),
  "provider" smallint NOT NULL,
  "provider_symbol" varchar(96) NOT NULL,
  "market_cap" numeric(38,2),
  "market_cap_rank" integer,
  "is_tracked" boolean NOT NULL DEFAULT false,
  "first_seen_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "updated_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "reference_price" numeric(19,8),
  "reference_price_utc" timestamp(0),
  "sector" varchar(64),
  "country" varchar(8),
  CONSTRAINT "PK__asset__D28B561DE5251B7F" PRIMARY KEY ("asset_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.autopilot_einstellung (
  "depot" varchar(16) NOT NULL,
  "aktiv" boolean NOT NULL DEFAULT false,
  "werte" integer NOT NULL DEFAULT 8,
  "max_anteil" numeric(5,4) NOT NULL DEFAULT 0.20,
  "hysterese" numeric(6,4) NOT NULL DEFAULT 0.0030,
  "takt" varchar(4) NOT NULL DEFAULT '1T',
  "waehrung" varchar(8) NOT NULL DEFAULT 'USD',
  "nemotron" boolean NOT NULL DEFAULT true,
  "updated_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "startkapital" numeric(18,2) NOT NULL DEFAULT 1000,
  "zaehlt" boolean NOT NULL DEFAULT false,
  CONSTRAINT "PK_autopilot_einstellung" PRIMARY KEY ("depot")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.autopilot_entscheidung (
  "entscheidung_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "lauf_id" integer NOT NULL,
  "asset_id" integer NOT NULL,
  "rang" integer NOT NULL,
  "punktzahl" double precision NOT NULL,
  "bestandteile" text,
  "trefferquote" double precision,
  "bewegung" double precision,
  "erwartungswert" double precision,
  "beschluss" varchar(20) NOT NULL,
  "grund" varchar(600),
  "betrag" numeric(18,2),
  "urteil" boolean,
  "urteil_text" varchar(2000),
  "ausgefuehrt" boolean NOT NULL DEFAULT false,
  "am_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  CONSTRAINT "PK_autopilot_entscheidung" PRIMARY KEY ("entscheidung_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.autopilot_lauf (
  "lauf_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "gestartet_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "beendet_utc" timestamp(0),
  "depot" varchar(16) NOT NULL,
  "geprueft" integer NOT NULL DEFAULT 0,
  "geschaefte" integer NOT NULL DEFAULT 0,
  "gebuehren" numeric(18,2) NOT NULL DEFAULT 0,
  "vermoegen" numeric(18,2),
  "handelstag" boolean NOT NULL DEFAULT true,
  "notiz" varchar(1000),
  CONSTRAINT "PK_autopilot_lauf" PRIMARY KEY ("lauf_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.bot_trigger_run (
  "run_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "started_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "finished_utc" timestamp(0),
  "von_utc" timestamp(0) NOT NULL,
  "note" varchar(500),
  CONSTRAINT "PK_bot_trigger_run" PRIMARY KEY ("run_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.bot_trigger_stat (
  "run_id" integer NOT NULL,
  "ausloeser" varchar(60) NOT NULL,
  "klasse" smallint NOT NULL,
  "ereignisse" integer NOT NULL,
  "werte" integer NOT NULL,
  "r1" double precision,
  "r5" double precision,
  "r20" double precision,
  "b1" double precision,
  "b5" double precision,
  "b20" double precision,
  "richtung1" double precision,
  "richtung5" double precision,
  "richtung20" double precision,
  "volumen_faktor" double precision,
  CONSTRAINT "PK_bot_trigger_stat" PRIMARY KEY ("run_id", "ausloeser", "klasse")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.corp_action (
  "asset_id" integer NOT NULL,
  "date" date NOT NULL,
  "action_type" smallint NOT NULL,
  "ratio_n" numeric(19,8),
  "ratio_d" numeric(19,8),
  "amount" numeric(19,8),
  "provider" smallint NOT NULL,
  "ingested_at_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  CONSTRAINT "PK_corp_action" PRIMARY KEY ("asset_id", "date", "action_type")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.crossing (
  "crossing_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "asset_id_a" integer NOT NULL,
  "asset_id_b" integer NOT NULL,
  "interval_code" varchar(3) NOT NULL,
  "ts_utc" timestamp(0) NOT NULL,
  "direction" smallint NOT NULL,
  "spread_before" double precision NOT NULL,
  "spread_after" double precision NOT NULL,
  "detected_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  CONSTRAINT "PK__crossing__FB234D9F0E4151BD" PRIMARY KEY ("crossing_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.curve_event (
  "curve_event_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "run_id" integer NOT NULL,
  "asset_id" integer NOT NULL,
  "ts_utc" timestamp(0) NOT NULL,
  "event_type" varchar(24) NOT NULL,
  "sign" smallint NOT NULL,
  "severity" double precision NOT NULL,
  "close_price" numeric(18,6) NOT NULL,
  "smoothed" numeric(18,6) NOT NULL,
  "slope" double precision NOT NULL,
  "curvature" double precision NOT NULL,
  CONSTRAINT "PK__curve_ev__69A1EE6BA7A82BBA" PRIMARY KEY ("curve_event_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.curve_link (
  "curve_link_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "run_id" integer NOT NULL,
  "asset_a" integer NOT NULL,
  "asset_b" integer NOT NULL,
  "type_a" varchar(24) NOT NULL,
  "type_b" varchar(24) NOT NULL,
  "pairs" integer NOT NULL,
  "expected" double precision NOT NULL,
  "lift" double precision NOT NULL,
  "median_lag_bars" double precision NOT NULL,
  "lead_share" double precision NOT NULL,
  "mean_severity" double precision NOT NULL,
  CONSTRAINT "PK__curve_li__C0F9AB66D8B1229E" PRIMARY KEY ("curve_link_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.curve_run (
  "run_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "started_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "finished_utc" timestamp(0),
  "interval_code" varchar(4) NOT NULL,
  "from_utc" timestamp(0),
  "to_utc" timestamp(0),
  "half_window" integer NOT NULL,
  "causal" boolean NOT NULL,
  "ref_window" integer NOT NULL,
  "min_z" double precision NOT NULL,
  "refractory" integer NOT NULL,
  "min_severity" double precision NOT NULL,
  "assets" integer NOT NULL DEFAULT 0,
  "events" integer NOT NULL DEFAULT 0,
  "note" varchar(400),
  CONSTRAINT "PK__curve_ru__7D3D901BB264A6FF" PRIMARY KEY ("run_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.forecast (
  "forecast_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "asset_id" integer NOT NULL,
  "horizon_hours" integer NOT NULL,
  "made_at_utc" timestamp(0) NOT NULL,
  "target_ts_utc" timestamp(0) NOT NULL,
  "base_close" numeric(19,8) NOT NULL,
  "predicted_close" numeric(19,8) NOT NULL,
  "predicted_return" double precision NOT NULL,
  "confidence" double precision NOT NULL,
  "contributions" text,
  "model_version" varchar(32) NOT NULL,
  "unscoreable_utc" timestamp(0),
  "unscoreable_reason" varchar(200),
  "combined_close" numeric(18,6),
  "combined_return" double precision,
  "pillar_mix" varchar(2000),
  CONSTRAINT "PK__forecast__9E57315422649F59" PRIMARY KEY ("forecast_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.forecast_component (
  "forecast_id" bigint NOT NULL,
  "model_name" varchar(32) NOT NULL,
  "predicted_return" double precision NOT NULL,
  "weight" double precision NOT NULL,
  CONSTRAINT "PK_forecast_component" PRIMARY KEY ("forecast_id", "model_name")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.forecast_score (
  "forecast_id" bigint NOT NULL,
  "actual_close" numeric(19,8) NOT NULL,
  "actual_return" double precision NOT NULL,
  "abs_pct_error" double precision NOT NULL,
  "direction_correct" boolean NOT NULL,
  "scored_at_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  CONSTRAINT "PK__forecast__9E5731541E1E9875" PRIMARY KEY ("forecast_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.forecast_score_combined (
  "forecast_id" bigint NOT NULL,
  "actual_close" numeric(18,6) NOT NULL,
  "actual_return" double precision NOT NULL,
  "abs_pct_error" double precision NOT NULL,
  "direction_correct" boolean,
  "scored_at_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  CONSTRAINT "PK_forecast_score_combined" PRIMARY KEY ("forecast_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.forecast_track (
  "asset_id" integer NOT NULL,
  "horizon_hours" integer NOT NULL,
  "interval_code" varchar(3) NOT NULL,
  "target_ts_utc" timestamp(0) NOT NULL,
  "made_at_utc" timestamp(0) NOT NULL,
  "base_close" numeric(19,8) NOT NULL,
  "predicted_close" numeric(19,8) NOT NULL,
  "actual_close" numeric(19,8),
  "abs_pct_error" double precision,
  "direction_correct" boolean,
  "confidence" double precision NOT NULL DEFAULT 0.5,
  "run_label" varchar(64) NOT NULL,
  CONSTRAINT "PK_forecast_track" PRIMARY KEY ("asset_id", "horizon_hours", "interval_code", "target_ts_utc")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.freq_match (
  "match_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "interval_code" varchar(3) NOT NULL,
  "epoch_to_utc" timestamp(0) NOT NULL,
  "asset_a" integer NOT NULL,
  "asset_b" integer NOT NULL,
  "period_a" double precision NOT NULL,
  "period_b" double precision NOT NULL,
  "period_delta" double precision NOT NULL,
  "phase_delta_deg" double precision,
  "lag_bars" double precision,
  "score" double precision NOT NULL,
  "created_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  CONSTRAINT "PK_freq_match" PRIMARY KEY ("match_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.freq_pattern (
  "pattern_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "asset_id" integer NOT NULL,
  "interval_code" varchar(3) NOT NULL,
  "epoch_from_utc" timestamp(0) NOT NULL,
  "epoch_to_utc" timestamp(0) NOT NULL,
  "period_bars" double precision NOT NULL,
  "prominence" double precision NOT NULL,
  "stability" double precision NOT NULL,
  "phase_deg" double precision,
  "amplitude" double precision,
  "created_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  CONSTRAINT "PK_freq_pattern" PRIMARY KEY ("pattern_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.holding (
  "holding_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "asset_id" integer NOT NULL,
  "kapital" numeric(18,2) NOT NULL,
  "waehrung" varchar(8) NOT NULL DEFAULT 'USD',
  "einstand" numeric(28,10),
  "gekauft_utc" timestamp(0),
  "notiz" varchar(400),
  "updated_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  CONSTRAINT "PK_holding" PRIMARY KEY ("holding_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.ingest_run (
  "run_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "job_name" varchar(100) NOT NULL,
  "provider" smallint,
  "started_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "finished_utc" timestamp(0),
  "ok_count" integer,
  "err_count" integer,
  "rows_written" integer,
  "note" varchar(4000),
  CONSTRAINT "PK__ingest_r__7D3D901B117DDA7C" PRIMARY KEY ("run_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.invest_buchung (
  "buchung_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "asset_id" integer NOT NULL,
  "am_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "kurs" numeric(28,10) NOT NULL,
  "kurs_utc" timestamp(0),
  "betrag" numeric(18,2) NOT NULL,
  "anteile" numeric(28,10) NOT NULL,
  "waehrung" varchar(8) NOT NULL DEFAULT 'EUR',
  "notiz" varchar(400),
  "gebuehr" numeric(18,2) NOT NULL DEFAULT 0,
  "depot" varchar(16) NOT NULL DEFAULT 'manuell',
  CONSTRAINT "PK_invest_buchung" PRIMARY KEY ("buchung_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.invest_konto (
  "waehrung" varchar(8) NOT NULL,
  "gebuehr_pct" numeric(6,4) NOT NULL DEFAULT 0.15,
  "updated_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "depot" varchar(16) NOT NULL DEFAULT 'manuell',
  CONSTRAINT "PK_invest_konto" PRIMARY KEY ("depot", "waehrung")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.invest_kontobewegung (
  "bewegung_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "waehrung" varchar(8) NOT NULL,
  "am_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "betrag" numeric(18,2) NOT NULL,
  "grund" varchar(20) NOT NULL,
  "buchung_id" integer,
  "notiz" varchar(400),
  "depot" varchar(16) NOT NULL DEFAULT 'manuell',
  CONSTRAINT "PK_invest_kontobewegung" PRIMARY KEY ("bewegung_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.knowledge_chunk (
  "chunk_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "source_id" integer NOT NULL,
  "ordinal" integer NOT NULL,
  "page_from" integer,
  "page_to" integer,
  "content" text NOT NULL,
  "tokens" integer NOT NULL DEFAULT 0,
  "occurred_utc" timestamp(0),
  "embedded_utc" timestamp(0),
  "vector_id" uuid NOT NULL DEFAULT (gen_random_uuid()),
  "chunk_hash" bytea,
  "char_from" integer,
  "char_to" integer,
  "anchor" varchar(200),
  CONSTRAINT "PK__knowledg__8B0F074DE25396D9" PRIMARY KEY ("chunk_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.knowledge_source (
  "source_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kind" varchar(12) NOT NULL,
  "pillar" varchar(12) NOT NULL,
  "title" varchar(400) NOT NULL,
  "origin" varchar(1000) NOT NULL,
  "origin_hash" bytea GENERATED ALWAYS AS (sha256(convert_to(origin, 'UTF8'))) STORED,
  "content_type" varchar(80),
  "bytes" bigint NOT NULL DEFAULT 0,
  "added_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "indexed_utc" timestamp(0),
  "last_checked_utc" timestamp(0),
  "active" boolean NOT NULL DEFAULT true,
  "poll_minutes" integer,
  "chunks" integer NOT NULL DEFAULT 0,
  "status" varchar(400),
  "content_hash" varchar(64),
  "parent_source_id" integer,
  "published_utc" timestamp(0),
  "region" varchar(60),
  CONSTRAINT "PK__knowledg__3035A9B6C2FAA93A" PRIMARY KEY ("source_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.learning_curve (
  "epoch_id" integer NOT NULL,
  "bucket_no" integer NOT NULL,
  "horizon_hours" integer NOT NULL,
  "from_utc" timestamp(0) NOT NULL,
  "to_utc" timestamp(0) NOT NULL,
  "n" integer NOT NULL,
  "mape" double precision NOT NULL,
  "hit_rate" double precision NOT NULL,
  CONSTRAINT "PK_learning_curve" PRIMARY KEY ("epoch_id", "bucket_no", "horizon_hours")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.learning_epoch (
  "epoch_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "run_label" varchar(64) NOT NULL,
  "pass_no" integer NOT NULL,
  "interval_code" varchar(3) NOT NULL,
  "horizons" varchar(100) NOT NULL,
  "started_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "finished_utc" timestamp(0),
  "assets" integer,
  "steps" integer,
  "forecasts" bigint,
  "scored" bigint,
  "mape" double precision,
  "hit_rate" double precision,
  "pair_refreshes" integer,
  "note" varchar(1000),
  CONSTRAINT "PK__learning__D4B38CD75091A864" PRIMARY KEY ("epoch_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.learning_model_curve (
  "epoch_id" integer NOT NULL,
  "bucket_no" integer NOT NULL,
  "model_name" varchar(32) NOT NULL,
  "avg_weight" double precision NOT NULL,
  "hit_rate" double precision NOT NULL,
  "mean_error" double precision NOT NULL,
  "n" integer NOT NULL,
  CONSTRAINT "PK_learning_model_curve" PRIMARY KEY ("epoch_id", "bucket_no", "model_name")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.model_weight (
  "asset_id" integer NOT NULL,
  "horizon_hours" integer NOT NULL,
  "model_name" varchar(32) NOT NULL,
  "weight" double precision NOT NULL,
  "n_obs" integer NOT NULL DEFAULT 0,
  "mean_abs_pct_err" double precision NOT NULL DEFAULT 0,
  "hit_rate" double precision NOT NULL DEFAULT 0.5,
  "updated_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  CONSTRAINT "PK_model_weight" PRIMARY KEY ("asset_id", "horizon_hours", "model_name")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.neuzugang (
  "neuzugang_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "quelle" varchar(24) NOT NULL,
  "art" varchar(12) NOT NULL,
  "symbol" varchar(40) NOT NULL,
  "name" varchar(200),
  "markt" varchar(60),
  "entdeckt_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "erwartet_am" date,
  "preis_von" numeric(18,6),
  "preis_bis" numeric(18,6),
  "volumen" numeric(20,2),
  "status" varchar(16) NOT NULL DEFAULT 'angekuendigt',
  "asset_id" integer,
  "erster_kurs" numeric(28,10),
  "erster_kurs_utc" timestamp(0),
  "url" varchar(500),
  "titel" varchar(400),
  "aktualisiert_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  CONSTRAINT "PK_neuzugang" PRIMARY KEY ("neuzugang_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.neuzugang_lauf (
  "lauf_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "gestartet_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "quelle" varchar(24) NOT NULL,
  "gefunden" integer NOT NULL DEFAULT 0,
  "neu" integer NOT NULL DEFAULT 0,
  "erfolg" boolean NOT NULL DEFAULT true,
  "meldung" varchar(500),
  CONSTRAINT "PK_neuzugang_lauf" PRIMARY KEY ("lauf_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.pair_stat (
  "asset_id_a" integer NOT NULL,
  "asset_id_b" integer NOT NULL,
  "interval_code" varchar(3) NOT NULL,
  "window_bars" integer NOT NULL,
  "corr0" double precision NOT NULL,
  "best_lag_bars" integer NOT NULL,
  "best_lag_corr" double precision NOT NULL,
  "n_obs" integer NOT NULL,
  "computed_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  CONSTRAINT "PK_pair_stat" PRIMARY KEY ("asset_id_a", "asset_id_b", "interval_code", "window_bars")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.pillar_skill (
  "pillar" varchar(30) NOT NULL,
  "horizon_hours" integer NOT NULL,
  "asset_id" integer NOT NULL DEFAULT 0,
  "skill" double precision NOT NULL,
  "n_obs" integer NOT NULL,
  "detail" varchar(500),
  "measured_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  CONSTRAINT "PK_pillar_skill" PRIMARY KEY ("pillar", "horizon_hours", "asset_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.pillar_weight (
  "pillar" varchar(32) NOT NULL,
  "weight" integer NOT NULL,
  "updated_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "begruendung" varchar(400),
  CONSTRAINT "PK_pillar_weight" PRIMARY KEY ("pillar")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.price_bar (
  "asset_id" integer NOT NULL,
  "interval_code" varchar(3) NOT NULL,
  "ts_utc" timestamp(0) NOT NULL,
  "open" numeric(19,8),
  "high" numeric(19,8),
  "low" numeric(19,8),
  "close" numeric(19,8) NOT NULL,
  "adj_close" numeric(19,8),
  "volume" numeric(38,8),
  "provider" smallint NOT NULL,
  "ingested_at_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  CONSTRAINT "PK_price_bar" PRIMARY KEY ("asset_id", "interval_code", "ts_utc")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.reasoning_log (
  "log_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "asked_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "user_id" integer,
  "frage" text NOT NULL,
  "antwort" text NOT NULL,
  "modell" varchar(200),
  "endpunkt" varchar(200),
  "sekunden" numeric(9,1),
  "runden" integer,
  "werkzeuge" text,
  "gemerkt" boolean NOT NULL DEFAULT false,
  "notiz" varchar(1000),
  CONSTRAINT "PK_reasoning_log" PRIMARY KEY ("log_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.reversal_pair (
  "run_id" integer NOT NULL,
  "asset_id_a" integer NOT NULL,
  "asset_id_b" integer NOT NULL,
  "n" integer NOT NULL,
  "hit_rate" double precision NOT NULL,
  "mean_gain" double precision NOT NULL,
  "z" double precision NOT NULL,
  "correlation" double precision,
  CONSTRAINT "PK_reversal_pair" PRIMARY KEY ("run_id", "asset_id_a", "asset_id_b")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.reversal_run (
  "run_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "started_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "finished_utc" timestamp(0),
  "interval_code" varchar(3) NOT NULL,
  "horizon_days" integer NOT NULL,
  "min_crossings" integer NOT NULL,
  "pairs_tested" integer NOT NULL DEFAULT 0,
  "mean_hit_rate" double precision,
  "sig_negative" integer,
  "sig_positive" integer,
  "expected_bychance" integer,
  "note" varchar(500),
  CONSTRAINT "PK_reversal_run" PRIMARY KEY ("run_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.timezone_lead_run (
  "run_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "started_utc" timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  "finished_utc" timestamp(0),
  "von_utc" timestamp(0) NOT NULL,
  "note" varchar(600),
  CONSTRAINT "PK_timezone_lead_run" PRIMARY KEY ("run_id")
);

-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dbo.timezone_lead_stat (
  "run_id" integer NOT NULL,
  "region_frueh" varchar(24) NOT NULL,
  "region_spaet" varchar(24) NOT NULL,
  "stunden_vorsprung" integer NOT NULL,
  "tage" integer NOT NULL,
  "werte_frueh" integer NOT NULL,
  "werte_spaet" integer NOT NULL,
  "korr_cc" double precision,
  "korr_gap" double precision,
  "korr_handelbar" double precision,
  "korr_gegenprobe" double precision,
  "stunden_ueberlappung" integer,
  CONSTRAINT "PK_timezone_lead_stat" PRIMARY KEY ("run_id", "region_frueh", "region_spaet")
);

-- ----------------------------------------------------------------------
-- Indizes
CREATE UNIQUE INDEX IF NOT EXISTS "UQ_app_user_login" ON dbo.app_user (LOWER("login"));
CREATE INDEX IF NOT EXISTS "IX_asset_sector" ON dbo.asset ("sector") INCLUDE ("asset_class", "symbol", "is_tracked");
CREATE INDEX IF NOT EXISTS "IX_asset_tracked" ON dbo.asset ("is_tracked", "asset_class") INCLUDE ("symbol", "market_cap_rank");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_asset_class_symbol" ON dbo.asset ("asset_class", "symbol");
CREATE INDEX IF NOT EXISTS "IX_ae_lauf_rang" ON dbo.autopilot_entscheidung ("lauf_id", "rang");
CREATE INDEX IF NOT EXISTS "IX_crossing_a_ts" ON dbo.crossing ("asset_id_a", "interval_code", "ts_utc") INCLUDE ("asset_id_b", "direction");
CREATE INDEX IF NOT EXISTS "IX_crossing_b_ts" ON dbo.crossing ("asset_id_b", "interval_code", "ts_utc") INCLUDE ("asset_id_a", "direction");
CREATE INDEX IF NOT EXISTS "IX_crossing_ts" ON dbo.crossing ("interval_code", "ts_utc") INCLUDE ("asset_id_a", "asset_id_b", "direction");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_crossing" ON dbo.crossing ("asset_id_a", "asset_id_b", "interval_code", "ts_utc");
CREATE INDEX IF NOT EXISTS "IX_curve_event_asset_ts" ON dbo.curve_event ("run_id", "asset_id", "ts_utc");
CREATE INDEX IF NOT EXISTS "IX_curve_event_run_sev" ON dbo.curve_event ("run_id", "severity" DESC) INCLUDE ("asset_id", "ts_utc", "event_type", "sign", "close_price");
CREATE INDEX IF NOT EXISTS "IX_curve_event_type_ts" ON dbo.curve_event ("run_id", "event_type", "ts_utc");
CREATE INDEX IF NOT EXISTS "IX_curve_link_a" ON dbo.curve_link ("run_id", "asset_a", "lift" DESC) INCLUDE ("asset_b", "type_a", "type_b", "pairs", "expected", "median_lag_bars", "lead_share", "mean_severity");
CREATE INDEX IF NOT EXISTS "IX_curve_link_b" ON dbo.curve_link ("run_id", "asset_b", "lift" DESC) INCLUDE ("asset_a", "type_a", "type_b", "pairs", "expected", "median_lag_bars", "lead_share", "mean_severity");
CREATE INDEX IF NOT EXISTS "IX_curve_link_run_lift" ON dbo.curve_link ("run_id", "lift" DESC) INCLUDE ("asset_a", "asset_b", "type_a", "type_b", "pairs", "median_lag_bars", "lead_share");
CREATE INDEX IF NOT EXISTS "IX_forecast_combined" ON dbo.forecast ("target_ts_utc") INCLUDE ("combined_close", "combined_return");
CREATE INDEX IF NOT EXISTS "IX_forecast_due" ON dbo.forecast ("target_ts_utc", "unscoreable_utc") INCLUDE ("asset_id", "horizon_hours", "made_at_utc", "base_close", "predicted_close", "predicted_return", "confidence", "model_version");
CREATE INDEX IF NOT EXISTS "IX_forecast_target" ON dbo.forecast ("target_ts_utc") INCLUDE ("asset_id", "horizon_hours");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_forecast" ON dbo.forecast ("asset_id", "horizon_hours", "made_at_utc");
CREATE INDEX IF NOT EXISTS "IX_ft_lookup" ON dbo.forecast_track ("asset_id", "horizon_hours", "target_ts_utc") INCLUDE ("predicted_close", "actual_close", "abs_pct_error", "direction_correct");
CREATE INDEX IF NOT EXISTS "IX_freq_match_lookup" ON dbo.freq_match ("interval_code", "epoch_to_utc", "score" DESC);
CREATE INDEX IF NOT EXISTS "IX_freq_pattern_lookup" ON dbo.freq_pattern ("interval_code", "epoch_to_utc", "period_bars") INCLUDE ("asset_id", "prominence", "stability", "phase_deg");
CREATE UNIQUE INDEX IF NOT EXISTS "UQ_freq_pattern" ON dbo.freq_pattern ("asset_id", "interval_code", "epoch_to_utc", "period_bars");
CREATE UNIQUE INDEX IF NOT EXISTS "UQ_holding_asset" ON dbo.holding ("asset_id");
CREATE INDEX IF NOT EXISTS "IX_ib_asset_am" ON dbo.invest_buchung ("asset_id", "am_utc") INCLUDE ("betrag", "anteile", "kurs", "waehrung");
CREATE INDEX IF NOT EXISTS "IX_ib_depot_asset" ON dbo.invest_buchung ("depot", "asset_id", "am_utc") INCLUDE ("betrag", "anteile", "kurs", "gebuehr", "waehrung");
CREATE INDEX IF NOT EXISTS "IX_ikb_depot_waehr" ON dbo.invest_kontobewegung ("depot", "waehrung", "am_utc") INCLUDE ("betrag", "grund");
CREATE INDEX IF NOT EXISTS "IX_ikb_waehr_am" ON dbo.invest_kontobewegung ("waehrung", "am_utc") INCLUDE ("betrag", "grund");
CREATE INDEX IF NOT EXISTS "IX_kc_occurred" ON dbo.knowledge_chunk ("occurred_utc") WHERE occurred_utc IS NOT NULL;
CREATE INDEX IF NOT EXISTS "IX_kc_source" ON dbo.knowledge_chunk ("source_id", "ordinal");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_kc_source_ordinal" ON dbo.knowledge_chunk ("source_id", "ordinal");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_kc_vector" ON dbo.knowledge_chunk ("vector_id");
CREATE INDEX IF NOT EXISTS "IX_ks_parent" ON dbo.knowledge_source ("parent_source_id", "added_utc" DESC) INCLUDE ("chunks", "indexed_utc", "title");
CREATE INDEX IF NOT EXISTS "IX_ks_pillar" ON dbo.knowledge_source ("pillar", "active", "added_utc" DESC);
CREATE INDEX IF NOT EXISTS "IX_ks_published" ON dbo.knowledge_source ("pillar", "published_utc" DESC) WHERE published_utc IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "UX_ks_origin" ON dbo.knowledge_source ("pillar", "origin_hash");
CREATE INDEX IF NOT EXISTS "IX_nz_erwartet" ON dbo.neuzugang ("status", "erwartet_am") INCLUDE ("symbol", "name", "markt", "quelle", "art");
CREATE UNIQUE INDEX IF NOT EXISTS "UQ_neuzugang" ON dbo.neuzugang ("quelle", "symbol");
CREATE INDEX IF NOT EXISTS "IX_ps_lead" ON dbo.pair_stat ("asset_id_b", "interval_code", "best_lag_bars") INCLUDE ("asset_id_a", "best_lag_corr");
CREATE INDEX IF NOT EXISTS "IX_price_bar_scan" ON dbo.price_bar ("interval_code", "ts_utc") INCLUDE ("close", "asset_id");
CREATE INDEX IF NOT EXISTS "IX_reasoning_log_zeit" ON dbo.reasoning_log ("asked_utc" DESC) INCLUDE ("modell", "sekunden", "gemerkt");
CREATE INDEX IF NOT EXISTS "IX_rp_z" ON dbo.reversal_pair ("run_id", "z");

-- ----------------------------------------------------------------------
-- Fremdschluessel
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_app_session_user') THEN
    ALTER TABLE dbo.app_session ADD CONSTRAINT "FK_app_session_user" FOREIGN KEY ("user_id") REFERENCES dbo.app_user ("user_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ae_asset') THEN
    ALTER TABLE dbo.autopilot_entscheidung ADD CONSTRAINT "FK_ae_asset" FOREIGN KEY ("asset_id") REFERENCES dbo.asset ("asset_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ae_lauf') THEN
    ALTER TABLE dbo.autopilot_entscheidung ADD CONSTRAINT "FK_ae_lauf" FOREIGN KEY ("lauf_id") REFERENCES dbo.autopilot_lauf ("lauf_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_bts_run') THEN
    ALTER TABLE dbo.bot_trigger_stat ADD CONSTRAINT "FK_bts_run" FOREIGN KEY ("run_id") REFERENCES dbo.bot_trigger_run ("run_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_corp_action_asset') THEN
    ALTER TABLE dbo.corp_action ADD CONSTRAINT "FK_corp_action_asset" FOREIGN KEY ("asset_id") REFERENCES dbo.asset ("asset_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_cx_a') THEN
    ALTER TABLE dbo.crossing ADD CONSTRAINT "FK_cx_a" FOREIGN KEY ("asset_id_a") REFERENCES dbo.asset ("asset_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_cx_b') THEN
    ALTER TABLE dbo.crossing ADD CONSTRAINT "FK_cx_b" FOREIGN KEY ("asset_id_b") REFERENCES dbo.asset ("asset_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_fc_asset') THEN
    ALTER TABLE dbo.forecast ADD CONSTRAINT "FK_fc_asset" FOREIGN KEY ("asset_id") REFERENCES dbo.asset ("asset_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_fcp_fc') THEN
    ALTER TABLE dbo.forecast_component ADD CONSTRAINT "FK_fcp_fc" FOREIGN KEY ("forecast_id") REFERENCES dbo.forecast ("forecast_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_fs_fc') THEN
    ALTER TABLE dbo.forecast_score ADD CONSTRAINT "FK_fs_fc" FOREIGN KEY ("forecast_id") REFERENCES dbo.forecast ("forecast_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_fsc_forecast') THEN
    ALTER TABLE dbo.forecast_score_combined ADD CONSTRAINT "FK_fsc_forecast" FOREIGN KEY ("forecast_id") REFERENCES dbo.forecast ("forecast_id") ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_freq_pattern_asset') THEN
    ALTER TABLE dbo.freq_pattern ADD CONSTRAINT "FK_freq_pattern_asset" FOREIGN KEY ("asset_id") REFERENCES dbo.asset ("asset_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_holding_asset') THEN
    ALTER TABLE dbo.holding ADD CONSTRAINT "FK_holding_asset" FOREIGN KEY ("asset_id") REFERENCES dbo.asset ("asset_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ib_asset') THEN
    ALTER TABLE dbo.invest_buchung ADD CONSTRAINT "FK_ib_asset" FOREIGN KEY ("asset_id") REFERENCES dbo.asset ("asset_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_kc_source') THEN
    ALTER TABLE dbo.knowledge_chunk ADD CONSTRAINT "FK_kc_source" FOREIGN KEY ("source_id") REFERENCES dbo.knowledge_source ("source_id") ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_lc_epoch') THEN
    ALTER TABLE dbo.learning_curve ADD CONSTRAINT "FK_lc_epoch" FOREIGN KEY ("epoch_id") REFERENCES dbo.learning_epoch ("epoch_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_lmc_epoch') THEN
    ALTER TABLE dbo.learning_model_curve ADD CONSTRAINT "FK_lmc_epoch" FOREIGN KEY ("epoch_id") REFERENCES dbo.learning_epoch ("epoch_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_mw_asset') THEN
    ALTER TABLE dbo.model_weight ADD CONSTRAINT "FK_mw_asset" FOREIGN KEY ("asset_id") REFERENCES dbo.asset ("asset_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_nz_asset') THEN
    ALTER TABLE dbo.neuzugang ADD CONSTRAINT "FK_nz_asset" FOREIGN KEY ("asset_id") REFERENCES dbo.asset ("asset_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ps_a') THEN
    ALTER TABLE dbo.pair_stat ADD CONSTRAINT "FK_ps_a" FOREIGN KEY ("asset_id_a") REFERENCES dbo.asset ("asset_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ps_b') THEN
    ALTER TABLE dbo.pair_stat ADD CONSTRAINT "FK_ps_b" FOREIGN KEY ("asset_id_b") REFERENCES dbo.asset ("asset_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_price_bar_asset') THEN
    ALTER TABLE dbo.price_bar ADD CONSTRAINT "FK_price_bar_asset" FOREIGN KEY ("asset_id") REFERENCES dbo.asset ("asset_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_reasoning_log_user') THEN
    ALTER TABLE dbo.reasoning_log ADD CONSTRAINT "FK_reasoning_log_user" FOREIGN KEY ("user_id") REFERENCES dbo.app_user ("user_id") ON DELETE SET NULL;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_rp_run') THEN
    ALTER TABLE dbo.reversal_pair ADD CONSTRAINT "FK_rp_run" FOREIGN KEY ("run_id") REFERENCES dbo.reversal_run ("run_id") ON DELETE NO ACTION;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_tzls_run') THEN
    ALTER TABLE dbo.timezone_lead_stat ADD CONSTRAINT "FK_tzls_run" FOREIGN KEY ("run_id") REFERENCES dbo.timezone_lead_run ("run_id") ON DELETE NO ACTION;
  END IF;
END $$;

-- ----------------------------------------------------------------------
-- Pruefbedingungen
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CK_app_state_kind') THEN
    ALTER TABLE dbo.app_state ADD CONSTRAINT "CK_app_state_kind" CHECK ((owner_kind=1 OR owner_kind=0));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CK_app_state_json') THEN
    ALTER TABLE dbo.app_state ADD CONSTRAINT "CK_app_state_json" CHECK ((pg_input_is_valid(payload, 'jsonb')));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CK_app_user_role') THEN
    ALTER TABLE dbo.app_user ADD CONSTRAINT "CK_app_user_role" CHECK (role='user' OR role='admin');
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CK_aes_takt') THEN
    ALTER TABLE dbo.autopilot_einstellung ADD CONSTRAINT "CK_aes_takt" CHECK (takt='1J' OR takt='6M' OR takt='3M' OR takt='1M' OR takt='1W' OR takt='1T');
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CK_freq_match_order') THEN
    ALTER TABLE dbo.freq_match ADD CONSTRAINT "CK_freq_match_order" CHECK (asset_a<asset_b);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CK_holding_kapital') THEN
    ALTER TABLE dbo.holding ADD CONSTRAINT "CK_holding_kapital" CHECK ((kapital>0));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CK_ib_kurs') THEN
    ALTER TABLE dbo.invest_buchung ADD CONSTRAINT "CK_ib_kurs" CHECK ((kurs>0));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CK_ib_betrag') THEN
    ALTER TABLE dbo.invest_buchung ADD CONSTRAINT "CK_ib_betrag" CHECK ((betrag<>0));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CK_ik_geb') THEN
    ALTER TABLE dbo.invest_konto ADD CONSTRAINT "CK_ik_geb" CHECK ((gebuehr_pct>=0 AND gebuehr_pct<=10));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CK_ikb_betrag') THEN
    ALTER TABLE dbo.invest_kontobewegung ADD CONSTRAINT "CK_ikb_betrag" CHECK ((betrag<>0));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CK_pw_weight') THEN
    ALTER TABLE dbo.pillar_weight ADD CONSTRAINT "CK_pw_weight" CHECK ((weight>=0 AND weight<=100));
  END IF;
END $$;
