-- 013 -- Der Katalog der Grundschwingungen. Gegenstueck zu infra/sql/044;
-- die Begruendung steht dort. Idempotent.
SET search_path = dbo, public;

CREATE TABLE IF NOT EXISTS dbo.freq_run (
  run_id        integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  interval_code varchar(3) NOT NULL,
  started_utc   timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  finished_utc  timestamp(0),
  werte         integer NOT NULL DEFAULT 0,
  epochen       integer NOT NULL DEFAULT 0,
  muster        integer NOT NULL DEFAULT 0,
  akkorde       integer NOT NULL DEFAULT 0,
  klassen       integer NOT NULL DEFAULT 0,
  paare         integer NOT NULL DEFAULT 0,
  paare_bestaendig integer NOT NULL DEFAULT 0,
  dauer_s       double precision,
  note          varchar(400),
  CONSTRAINT "PK_freq_run" PRIMARY KEY (run_id)
);

CREATE TABLE IF NOT EXISTS dbo.freq_class (
  class_id      integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  run_id        integer NOT NULL REFERENCES dbo.freq_run(run_id),
  nr            integer NOT NULL,
  stimmen       smallint NOT NULL,
  periode1      double precision NOT NULL,
  periode2      double precision,
  periode3      double precision,
  amp2          double precision,
  amp3          double precision,
  harmonik      varchar(12) NOT NULL,
  akkorde       integer NOT NULL,
  werte         integer NOT NULL,
  epochen       integer NOT NULL,
  prominenz     double precision NOT NULL,
  stabilitaet   double precision NOT NULL,
  paare         integer NOT NULL DEFAULT 0,
  paare_bestaendig integer NOT NULL DEFAULT 0,
  CONSTRAINT "PK_freq_class" PRIMARY KEY (class_id)
);

CREATE TABLE IF NOT EXISTS dbo.freq_akkord (
  akkord_id     bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  run_id        integer NOT NULL REFERENCES dbo.freq_run(run_id),
  class_id      integer,
  asset_id      integer NOT NULL REFERENCES dbo.asset(asset_id),
  epoch_from_utc timestamp(0) NOT NULL,
  epoch_to_utc  timestamp(0) NOT NULL,
  periode1      double precision NOT NULL,
  periode2      double precision,
  periode3      double precision,
  amp2          double precision,
  amp3          double precision,
  phase1        double precision NOT NULL,
  phase2        double precision,
  phase3        double precision,
  prominenz     double precision NOT NULL,
  stabilitaet   double precision NOT NULL,
  CONSTRAINT "PK_freq_akkord" PRIMARY KEY (akkord_id)
);
CREATE INDEX IF NOT EXISTS "IX_freq_akkord_class" ON dbo.freq_akkord (class_id, asset_id) INCLUDE (epoch_to_utc, phase1);
CREATE INDEX IF NOT EXISTS "IX_freq_akkord_asset" ON dbo.freq_akkord (asset_id, epoch_to_utc) INCLUDE (class_id);

ALTER TABLE dbo.freq_match ADD COLUMN IF NOT EXISTS run_id integer;
ALTER TABLE dbo.freq_match ADD COLUMN IF NOT EXISTS class_id integer;
ALTER TABLE dbo.freq_match ADD COLUMN IF NOT EXISTS epochs integer;
ALTER TABLE dbo.freq_match ADD COLUMN IF NOT EXISTS lag_sd double precision;
ALTER TABLE dbo.freq_match ADD COLUMN IF NOT EXISTS bestaendig boolean;
CREATE INDEX IF NOT EXISTS "IX_freq_match_class" ON dbo.freq_match (class_id, bestaendig);

ALTER TABLE dbo.freq_pattern ADD COLUMN IF NOT EXISTS run_id integer;
