-- 014 -- Urteile der Reasoning-Saeule. Gegenstueck zu infra/sql/045; die
-- Begruendung steht dort. Idempotent.
SET search_path = dbo, public;

CREATE TABLE IF NOT EXISTS dbo.reasoning_urteil (
  urteil_id     bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  asset_id      integer NOT NULL REFERENCES dbo.asset(asset_id),
  made_at_utc   timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  modell        varchar(64) NOT NULL,
  richtung      smallint NOT NULL CHECK (richtung BETWEEN -2 AND 2),
  zuversicht    double precision NOT NULL CHECK (zuversicht BETWEEN 0 AND 1),
  begruendung   varchar(600),
  werkzeuge     varchar(200) NOT NULL,
  runden        integer NOT NULL,
  sekunden      double precision NOT NULL,
  base_close    numeric(18,8) NOT NULL,
  bewertet_utc  timestamp(0),
  realisiert    double precision,
  treffer       boolean,
  CONSTRAINT "PK_reasoning_urteil" PRIMARY KEY (urteil_id)
);
CREATE INDEX IF NOT EXISTS "IX_reasoning_urteil_asset" ON dbo.reasoning_urteil (asset_id, made_at_utc DESC) INCLUDE (richtung, zuversicht, begruendung);
CREATE INDEX IF NOT EXISTS "IX_reasoning_urteil_offen" ON dbo.reasoning_urteil (bewertet_utc, made_at_utc) INCLUDE (asset_id, richtung, base_close);

INSERT INTO dbo.pillar_weight (pillar, weight, begruendung) VALUES
  ('reasoning', 0, 'Urteil des Agenten als Auf-/Abschlag; Betrag aus der Schwankung des Werts, Verdienst aus der Trefferquote nachgeprüfter Urteile.')
ON CONFLICT (pillar) DO NOTHING;
