-- 015 -- Der Hausmeister. Gegenstueck zu infra/sql/046; die Begruendung und
-- die gemessenen Zahlen stehen dort. Idempotent.
SET search_path = dbo, public;

CREATE TABLE IF NOT EXISTS dbo.housekeeping_lauf (
  lauf_id       integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  gestartet_utc timestamp(0) NOT NULL DEFAULT ((now() at time zone 'utc')),
  beendet_utc   timestamp(0),
  probe         boolean NOT NULL DEFAULT TRUE,
  ausgeloest    varchar(16) NOT NULL DEFAULT 'tageslauf',
  regeln        integer NOT NULL DEFAULT 0,
  zeilen        bigint NOT NULL DEFAULT 0,
  dauer_s       double precision,
  note          varchar(400),
  CONSTRAINT "PK_housekeeping_lauf" PRIMARY KEY (lauf_id)
);

CREATE TABLE IF NOT EXISTS dbo.housekeeping_regel (
  regel_id      integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lauf_id       integer NOT NULL REFERENCES dbo.housekeeping_lauf(lauf_id),
  schluessel    varchar(40) NOT NULL,
  tabelle       varchar(64) NOT NULL,
  frist_tage    integer NOT NULL,
  zeilen        bigint NOT NULL DEFAULT 0,
  dauer_s       double precision,
  fehler        varchar(400),
  CONSTRAINT "PK_housekeeping_regel" PRIMARY KEY (regel_id)
);
CREATE INDEX IF NOT EXISTS "IX_housekeeping_regel_lauf" ON dbo.housekeeping_regel (lauf_id, schluessel);
CREATE INDEX IF NOT EXISTS "IX_forecast_unscoreable" ON dbo.forecast (unscoreable_utc, target_ts_utc);
